---
kind: pipeline
name: default


workspace:
  base: /go
  path: src/github.com/morningconsult/go-elasticsearch-alerts

steps:
- name: test
  image: golang
  commands:
  - go get
  - make test
---
kind: signature
hmac: ef06a301e605821f6b1320b2a6dc4e12c789f9c14d5a180cd817659ce2ce8e14

...
